# Generated by Django 2.2.16 on 2022-04-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_title_genre'),
        ('titles', '0003_auto_20220418_1850'),
    ]

    operations = [
    ]
