# Generated by Django 2.2.16 on 2022-04-22 06:23

import django.core.validators
from django.db import migrations, models
import titles.models


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0004_merge_20220419_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(default=2022, validators=[django.core.validators.MinValueValidator(1984), titles.models.max_value_current_year]),
        ),
    ]
