# Generated by Django 2.2.16 on 2022-04-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20220417_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_author_title',
        ),
    ]
